// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Rahnavard724.Core.Data.DatabaseContext;
using System;

namespace Iran.AspNet.CountryDivisions.Migrations
{
    [DbContext(typeof(LocationsDbContext))]
    [Migration("20201229094116_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("Iran.AspNet.CountryDivisions.Data.Models.Abadi", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AbadiType");

                    b.Property<string>("AmarCode");

                    b.Property<string>("BakhshId");

                    b.Property<string>("DehestanId");

                    b.Property<string>("Diag");

                    b.Property<string>("Name");

                    b.Property<string>("OstanId");

                    b.Property<string>("ShahrestanId");

                    b.HasKey("Id");

                    b.ToTable("Abadis");
                });

            modelBuilder.Entity("Iran.AspNet.CountryDivisions.Data.Models.Bakhsh", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AmarCode");

                    b.Property<string>("Name");

                    b.Property<string>("OstanId");

                    b.Property<string>("ShahrestanId");

                    b.HasKey("Id");

                    b.ToTable("Bakhshs");
                });

            modelBuilder.Entity("Iran.AspNet.CountryDivisions.Data.Models.Dehestan", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AmarCode");

                    b.Property<string>("BakhshId");

                    b.Property<string>("Name");

                    b.Property<string>("OstanId");

                    b.Property<string>("ShahrestanId");

                    b.HasKey("Id");

                    b.ToTable("Dehestans");
                });

            modelBuilder.Entity("Iran.AspNet.CountryDivisions.Data.Models.Ostan", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AmarCode");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Ostans");
                });

            modelBuilder.Entity("Iran.AspNet.CountryDivisions.Data.Models.Shahr", b =>
                {
                    b.Property<string>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AmarCode");

                    b.Property<string>("BakhshId");

                    b.Property<string>("Name");

                    b.Property<string>("OstanId");

                    b.Property<string>("ShahrType");

                    b.Property<string>("ShahrestanId");

                    b.HasKey("id");

                    b.ToTable("Shahrs");
                });

            modelBuilder.Entity("Iran.AspNet.CountryDivisions.Data.Models.Shahrestan", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AmarCode");

                    b.Property<string>("Name");

                    b.Property<string>("OstanId");

                    b.HasKey("Id");

                    b.ToTable("Shahrestans");
                });
#pragma warning restore 612, 618
        }
    }
}
